# see https://goreleaser.com
before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    # https://pkg.go.dev/cmd/link
    ldflags:
      # remove symbol table and debug information
      - -s -w
      - -X github.com/hckops/hckctl/internal/command/version.release={{ .Version }}
      - -X github.com/hckops/hckctl/internal/command/version.commit={{ .ShortCommit }}
      - -X github.com/hckops/hckctl/internal/command/version.timestamp={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # overrides default to include only the binary in the archive
    files:
      - none*
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
