# see https://goreleaser.com
before:
  hooks:
    - go mod tidy

builds:
  - main: ./internal/main.go
    env:
      - CGO_ENABLED=0
    # https://pkg.go.dev/cmd/link
    ldflags:
      # remove symbol table and debug information
      - -s -w
      - -X github.com/hckops/hckctl/internal/command/version.release={{ .Version }}
      - -X github.com/hckops/hckctl/internal/command/version.commit={{ .ShortCommit }}
      - -X github.com/hckops/hckctl/internal/command/version.timestamp={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # overrides default to include only the binary in the archive
    files:
      - none*
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

brews:
  - name: hckctl
    repository:
      owner: hckops
      name: homebrew-tap
    commit_author:
      name: hckbot
      email: hckbot@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/hckops/hckctl
    description: "The declarative HaCKing Tool"
    skip_upload: false
    dependencies:
      - name: docker
        type: optional
      - name: kubectl
        type: optional
    test: |-
      hckctl version
