name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # required for GoReleaser
          fetch-depth: 0

      # required for GoReleaser
      - name: Fetch
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          # https://goreleaser.com/errors/resource-not-accessible-by-integration
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

      - name: Notification
        uses: hckops/actions/discord-action@v0.11.0
        with:
          action: create-message
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "> Repository:  **${{ github.repository }}**\\n> Version:\\t\\t ${{ github.ref_name }}\\n> Status:\\t\\t  **NEW release**"
